### ISSUE TITLE
Decouple from awesome_print

### ISSUE THREAD

**Issue by HarlemSquirrel** [awesomer-print/awesomer_print#5]
While we've made some head way already, it would be nice to remove the upstream reference since opening pull requests is defaulting against awesome_print.

We also have revision history that may no longer be relevant.

**Comment by HarlemSquirrel** [comment]
I sent a message to GitHub support about this.

**Comment by paddor** [comment]
Maybe we'll just have to create a fresh repository.

**Comment by HarlemSquirrel** [comment]
They detached it!

**Comment by paddor** [comment]
Great!
