### ISSUE TITLE
rails ActiveModel::Attributes support

### ISSUE THREAD

**Issue by james-caresnap** [awesomer-print/awesomer_print#85]
I have some rails models with custom Postgres jsonb attributes which are serialized/deserialized using the Attributes API. In other words, they are POROs with the following mixins:
- `ActiveModel::Model`
- `ActiveModel::Attributes`
- `ActiveModel::Serialization`

It looks like amazing_print just dumps these by calling `inspect` on them. What's the right way to add support to amazing print for these types? Add something to `amazing_print/lib/amazing_print/ext/`? Or modify the ActiveRecord extension? It looks like maybe you could just add another switch case [here](https://github.com/amazing-print/amazing_print/blob/master/lib/amazing_print/ext/active_record.rb#L21)?

**Comment by HarlemSquirrel** [comment]
Hey @james-caresnap sorry for the super delayed response but this sounds like a great idea! Sounds like ActiveRecord extension should be fine for this. I welcome a pull request!
